job_portal_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls')),
    path('',include('subscribe.urls'))
]

jobapp/urls.py
from django.urls import path
from jobapp import views

urlpatterns = [
    path('',views.job_list,name="jobs_home"),
    path('job/<int:id>-<slug>',views.job_detail,name="jobs_detail")
]

subscribe/urls.py
from django.urls import path
from subscribe import views

urlpatterns = [
    path('subscribe/',views.subscribe,name='subscribe'),
    path('thank_you',views.thank_you,name='thank_you')
]

jobapp/models.py
from django.db import models
from django.utils.text import slugify

JOB_OPTION = [
    ('F','Full time'),
    ('P','Part time'),
]
# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=75)
    designation = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['name','designation','company'],name='Author_unique_combination'
            )
        ]
    def __str__(self) -> str:
        return {'Author':self.name,'Designation':self.designation,'Company':self.company}

class JobLocation(models.Model):
    city = models.CharField(max_length=75)
    state = models.CharField(max_length=75)
    country = models.CharField(max_length=80)
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['city','state','country'],name='Job_location_unique_combination'
            )
        ]
    def __str__(self) -> str:
        return f'{self.city}, {self.state}, {self.country}'

class Skills(models.Model):
    class Meta:
        verbose_name_plural = "Skills"
    skill = models.CharField(max_length=200,unique=True) 

    def __str__(self) -> str:
        return self.skill

class JobPost(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    salary = models.IntegerField()
    job_location = models.ManyToManyField(JobLocation)
    date_posted = models.DateField(auto_now_add=True)
    skills = models.ManyToManyField(Skills)
    job_option = models.CharField(max_length=1,choices=JOB_OPTION,default='F')
    expiry = models.DateField(null=True)

    slug = models.SlugField(max_length=40,null=True,unique=True)

    def job_location_city_names(self):
        return ', '.join([c.city for c in self.job_location.all()])
    job_location_city_names.short_description = "City"

    def job_skills(self):
        return [s.skill for s in self.skills.all()]
    job_skills.short_description = "Skills"


    def save(self,*args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        return super(JobPost,self).save(*args,**kwargs)
    
    def __str__(self):
        return f'{self.title} with salary of {self.salary}'

    

subscribe/models.py
from django.db import models

# Create your models here.
NEWSLETTER_OPTION = [
    ('M','Monthly'),
    ('W','Weekly')
]

class Subscribe(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100,unique=True)
    option = models.CharField(max_length=1,choices=NEWSLETTER_OPTION,default='M')

subscribe/forms.py
from django import forms
from subscribe.models import Subscribe

class SubscribeForm(forms.ModelForm):
    
    class Meta:
        model = Subscribe
        fields = '__all__'
        labels = {
            'first_name':'Enter First name',
            'last_name':'Enter last name',
            'email':'Enter email',
            'option':'Newsletter option'
        }
        help_texts = {
            'first_name':'Enter characters only'
        }

        error_messages = {
            'first_name':{
                'required':'You cannot move forward without first name'
            },
            'email':{
                'unique':'Email already exists in our subscription list'
            }
        }

jobapp/views.py
from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render
from django.urls import reverse

from jobapp.models import JobPost

# Create your views here.
def job_list(request):
    jobs = JobPost.objects.all()
    return render(request,'jobapp/index.html',{'jobs':jobs})

def job_detail(request, id, slug):
    try:
        if id==0:
            return redirect(reverse('jobs_home'))
        job=JobPost.objects.get(id = id)
        return render(request,'jobapp/job_detail.html',{'job':job})
    except:
        return HttpResponseNotFound('Not found')

subscribe/views.py
from django.shortcuts import redirect, render
from django.urls import reverse

from subscribe.forms import SubscribeForm

# Create your views here.
def subscribe(request):
    subscribe_form = SubscribeForm()
    if request.POST:
        subscribe_form = SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            subscribe_form.save()
            return redirect(reverse('thank_you'))
    
    context = {'form':subscribe_form}
    return render(request,'subscribe/subscribe.html',context)

def thank_you(request):
    return render(request,'subscribe/thank_you.html',{})

jobapp/templates/jobapp/index.html
{% extends 'base.html' %}
{% block title %}FlixCareers | Home{% endblock title %}
{% block content %}
   <!-- job post lists -->
   <section>
    <div class="container">
      <!-- job post -->
      {% for job in jobs %}
      <div class="post">
        <!-- title and des -->
        <div class="job-info">
          <h1 class="job-title">{{job.title}}</h1>
          <div class="job-des">
            <div class="location item">
              <span class="material-icons"> place </span>
              <p>{{job.job_location_city_names|truncatechars:"30"}}</p>
            </div>
            <div class="budget item">
              <span class="material-icons"> attach_money </span>
              <p>{{job.salary}}/Pm</p>
            </div>
            <div class="time item">
              <span class="material-icons"> schedule </span>
              <p>{{job.get_job_option_display}}</p>
            </div>
          </div>
        </div>
        <div class="buttons">
          <button class="apply">
            <a href="{% url 'jobs_detail' job.id job.slug %}">View Job</a>
          </button>
        </div>
      </div>
      <!-- job post end-->
      {% endfor %}
    </div>
  </section>
{% endblock content %}

jobapp/templates/jobapp/job_detail.html
{% extends 'base.html' %}
{% block title %}FlixCareers | {{job.title}}{% endblock title %}
{% block content %}
<section>
  <div class="container">
    <div class="view-post">
      <h1 class="jobtitle">
        {{ job.title }}
      </h1>
      <p class="location it">Location: <span>{{job.job_location_city_names}}</span></p>
      <p class="status it">Type: <span>{{job.get_job_option_display}}</span></p>
      <p class="budget it">Salary: <span>{{job.salary}}</span></p>
      <div class="desc">
        <p class="details">
          {{job.description}}
        </p>
      </div>
      <p class="skills it">Skills
      <ul>
        {% for skill in job.job_skills %}
          <li>{{skill}}</li>
        {% endfor %}
      </p>
    </ul>
    </div>
  </div>
</section>
{% endblock content %}

subscribe/templates/subscribe/subscribe.html
{% extends 'base.html' %}
{% block title %}FlixCareers|Subscribe{% endblock title %}
{% block content%}
<section>
    <div class="container">
        <form class="email-form" method="post">
          {% csrf_token %}
          {% comment %} {{ form.as_p }} {% endcomment %}
          {% for field in form %}
              {{field.errors}}
              <p><label for="{{field.id_for_label}}">{{field.label}}</label>
                  {{field}}
              </p>
          {% endfor %}
          <input type="submit" value="Submit" class="email-submit">
        </form>
    </div>
  </section>
{% endblock content %}

subscribe/templates/subscribe/thank_you.html
{% extends 'base.html' %}
{% block title %}FlixCareers|Thank You{% endblock title %}
{% block content %}
    <div class="container thank-you">
        <section>
            <p>Thank you for your submission</p>
        </section>
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'jobapp/main.css' %}" />
    <link
      href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
      rel="stylesheet"
    />

    <title>{% block title %}Job Website{% endblock title %}</title>
  </head>
  <body>
    <header>
      <nav>
        <div class="container">
          <div class="logo">
            <img src="{% static 'jobapp/logo.svg' %}" alt="" />
          </div>
          <div class="links">
            <a href="{% url 'jobs_home' %}">Home</a>
            <a href="{% url 'subscribe' %}">Subscribe</a>
          </div>
          <span class="material-icons menu" onclick="menu()"> menu </span>
        </div>
      </nav>
    </header>

    {% block content %}
    {% endblock content %}
    <script src="{% static 'jobapp/jobapp.js' %}"></script>
  </body>
</html>